/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Presets = {
  presetName: string;
  name: string;
  position: string;
  name2: string;
  position2: string;
  society: string;
  societySocials: string;
}[];
